### ISSUE TITLE
Create mobile application.

### ISSUE THREAD

**Issue by THISARA005** [malshan-weerasinghe/System-Integration-Technologies-Group-project-#3]
Include address page, cart page, contact us page, drawer page, favourite page, home page.intro page, item page,locaiton page, login page, preview page, profile page, promotion page, purchase history page, settings page, signup page, thank you page.

**Comment by malshan-weerasinghe** [comment]
completed the mobile app

**Comment by ashenshanuka** [comment]
Mobile app created using flutter and integrated to the website.✔️
